// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentApp.Data;

#nullable disable

namespace RecruitmentApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605092536_UpdateColumsTypes")]
    partial class UpdateColumsTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentApp.Models.Biodata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AlamatKtp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AlamatTinggal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("BersediaDitempatkan")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("GajiDiharapkan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GolonganDarah")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KontakDarurat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NoKtp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NoTelp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PosisiDilamar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Skill")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TempatLahir")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Biodatas");
                });

            modelBuilder.Entity("RecruitmentApp.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BiodataId")
                        .HasColumnType("int");

                    b.Property<decimal>("IPK")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Institusi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Jenjang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Jurusan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TahunLulus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BiodataId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("RecruitmentApp.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BiodataId")
                        .HasColumnType("int");

                    b.Property<string>("NamaKursus")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sertifikat")
                        .HasColumnType("longtext");

                    b.Property<int>("Tahun")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BiodataId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("RecruitmentApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RecruitmentApp.Models.WorkExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BiodataId")
                        .HasColumnType("int");

                    b.Property<string>("NamaPerusahaan")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PendapatanTerakhir")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PosisiTerakhir")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Tahun")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BiodataId");

                    b.ToTable("WorkExperiences");
                });

            modelBuilder.Entity("RecruitmentApp.Models.Biodata", b =>
                {
                    b.HasOne("RecruitmentApp.Models.User", "User")
                        .WithOne("Biodata")
                        .HasForeignKey("RecruitmentApp.Models.Biodata", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentApp.Models.Education", b =>
                {
                    b.HasOne("RecruitmentApp.Models.Biodata", "Biodata")
                        .WithMany("Educations")
                        .HasForeignKey("BiodataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biodata");
                });

            modelBuilder.Entity("RecruitmentApp.Models.Training", b =>
                {
                    b.HasOne("RecruitmentApp.Models.Biodata", "Biodata")
                        .WithMany("Trainings")
                        .HasForeignKey("BiodataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biodata");
                });

            modelBuilder.Entity("RecruitmentApp.Models.WorkExperience", b =>
                {
                    b.HasOne("RecruitmentApp.Models.Biodata", "Biodata")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("BiodataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biodata");
                });

            modelBuilder.Entity("RecruitmentApp.Models.Biodata", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Trainings");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("RecruitmentApp.Models.User", b =>
                {
                    b.Navigation("Biodata");
                });
#pragma warning restore 612, 618
        }
    }
}
